// export const LANGUAGES = ["fr", "en", "es", "it", "de"];

import { t } from "i18next";
import { LanguageObj, Link } from "./types";


export const LANGUAGES: LanguageObj[] = [
    { code: "en", flag: "gb", name: "language.english" },
    { code: "fr", flag: "fr", name: "language.french" },
    { code: "es", flag: "es", name: "language.spanish" },
];

export const MAX_HEARTS = 5;

export const LINKS: Link[] = [
    {
        text_fr: 'Youtube - VIVRE MAROC',
        text_en: 'Youtube - VIVRE MAROC',
        text_es: 'Youtube - VIVRE MAROC',

        icon: 'logo-youtube',
        url: 'www.youtube.com',
        color: ''
    },
    {
        text_fr: 'Mon Ebook "Partir Vivre au Maroc"',
        text_en: 'My Ebook "Partir Vivre au Maroc"',
        text_es: 'Mi Ebook "Partir Vivre au Maroc"',

        icon: 'book',
        url: 'www.youtube.com',
        color: ''
    },
    {
        text_fr: 'Contacter Le Support 24/7',
        text_en: 'Contact Support 24/7',
        text_es: 'Contactar Soporte 24/7',

        icon: 'mail',
        url: 'www.youtube.com',
        color: ''
    },
]

export const hours = [
    { value: 0, label: "00" },
    { value: 1, label: "01" },
    { value: 2, label: "02" },
    { value: 3, label: "03" },
    { value: 4, label: "04" },
    { value: 5, label: "05" },
    { value: 6, label: "06" },
    { value: 7, label: "07" },
    { value: 8, label: "08" },
    { value: 9, label: "09" },
    { value: 10, label: "10" },
    { value: 11, label: "11" },
    { value: 12, label: "12" },
    { value: 13, label: "13" },
    { value: 14, label: "14" },
    { value: 15, label: "15" },
    { value: 16, label: "16" },
    { value: 17, label: "17" },
    { value: 18, label: "18" },
    { value: 19, label: "19" },
    { value: 20, label: "20" },
    { value: 21, label: "21" },
    { value: 22, label: "22" },
    { value: 23, label: "23" },
];

export const EVENTS = {
    subscription: "subscription",
    refill_hearts: "refill_hearts",
};

export const authErrors: { [key: string]: { [language: string]: string } } = {
    "admin-restricted-operation": {
        en: "This operation is restricted to administrators only.",
        fr: "Cette opération est réservée aux administrateurs uniquement.",
        es: "Esta operación está restringida solo a administradores.",
        it: "Questa operazione è riservata esclusivamente agli amministratori.",
        de: "Dieser Vorgang ist nur für Administratoren zulässig.",
    },
    "app-not-authorized": {
        en: "This app, identified by the domain where it's hosted, is not authorized to use Firebase Authentication with the provided API key. Review your key configuration in the Google API console.",
        fr: "Cette application, identifiée par le domaine où elle est hébergée, n'est pas autorisée à utiliser l'authentification Firebase avec la clé API fournie. Vérifiez la configuration de votre clé dans la console API de Google.",
        es: "Esta aplicación, identificada por el dominio donde está alojada, no está autorizada a usar Firebase Authentication con la clave API proporcionada. Revisa la configuración de tu clave en la consola de la API de Google.",
        it: "Questa app, identificata dal dominio in cui è ospitata, non è autorizzata a utilizzare Firebase Authentication con la chiave API fornita. Controlla la configurazione della chiave nella console API di Google.",
        de: "Diese App, die durch die Domain identifiziert wird, in der sie gehostet wird, ist nicht berechtigt, Firebase Authentication mit dem angegebenen API-Schlüssel zu verwenden. Überprüfen Sie Ihre Schlüsselkonfiguration in der Google API-Konsole.",
    },
    "app-not-installed": {
        en: "The requested mobile application corresponding to the identifier (Android package name or iOS bundle ID) provided is not installed on this device.",
        fr: "L'application mobile demandée correspondant à l'identifiant (nom du package Android ou ID du bundle iOS) fourni n'est pas installée sur cet appareil.",
        es: "La aplicación móvil solicitada correspondiente al identificador (nombre del paquete de Android o ID del paquete de iOS) proporcionado no está instalada en este dispositivo.",
        it: "L'applicazione mobile richiesta corrispondente all'identificatore (nome del pacchetto Android o ID del bundle iOS) fornito non è installata su questo dispositivo.",
        de: "Die angeforderte mobile Anwendung, die der angegebenen Kennung (Android-Paketname oder iOS-Bundle-ID) entspricht, ist auf diesem Gerät nicht installiert.",
    },
    "captcha-check-failed": {
        en: "The reCAPTCHA response token provided is either invalid, expired, already used or the domain associated with it does not match the list of whitelisted domains.",
        fr: "Le jeton de réponse reCAPTCHA fourni est soit invalide, expiré, déjà utilisé, soit le domaine qui lui est associé ne correspond pas à la liste des domaines sur liste blanche.",
        es: "El token de respuesta de reCAPTCHA proporcionado no es válido, expiró, ya se usó o el dominio asociado no coincide con la lista de dominios permitidos.",
        it: "Il token di risposta reCAPTCHA fornito non è valido, è scaduto, è già stato utilizzato o il dominio a esso associato non corrisponde all'elenco dei domini consentiti.",
        de: "Das angegebene reCAPTCHA-Antworttoken ist entweder ungültig, abgelaufen, bereits verwendet oder die zugehörige Domain stimmt nicht mit der Liste der Whitelist-Domains überein.",
    },
    "code-expired": {
        en: "The SMS code has expired. Please re-send the verification code to try again.",
        fr: "Le code SMS a expiré. Veuillez renvoyer le code de vérification pour réessayer.",
        es: "El código SMS expiró. Vuelve a enviar el código de verificación para intentarlo de nuevo.",
        it: "Il codice SMS è scaduto. Invia nuovamente il codice di verifica per riprovare.",
        de: "Der SMS-Code ist abgelaufen. Bitte senden Sie den Bestätigungscode erneut, um es erneut zu versuchen.",
    },
    "cordova-not-ready": {
        en: "Cordova framework is not ready.",
        fr: "Le framework Cordova n'est pas prêt.",
        es: "El framework de Cordova no está listo.",
        it: "Il framework Cordova non è pronto.",
        de: "Cordova-Framework ist nicht bereit.",
    },
    "cors-unsupported": {
        en: "This browser is not supported.",
        fr: "Ce navigateur n'est pas pris en charge.",
        es: "Este navegador no es compatible.",
        it: "Questo browser non è supportato.",
        de: "Dieser Browser wird nicht unterstützt.",
    },
    "credential-already-in-use": {
        en: "This credential is already associated with a different user account.",
        fr: "Cet identifiant est déjà associé à un autre compte utilisateur.",
        es: "Esta credencial ya está asociada con una cuenta de usuario diferente.",
        it: "Queste credenziali sono già associate a un account utente diverso.",
        de: "Diese Anmeldedaten sind bereits mit einem anderen Benutzerkonto verknüpft.",
    },
    "custom-token-mismatch": {
        en: "The custom token corresponds to a different audience.",
        fr: "Le token personnalisé correspond à une audience différente.",
        es: "El token personalizado corresponde a una audiencia diferente.",
        it: "Il token personalizzato corrisponde a un pubblico diverso.",
        de: "Das benutzerdefinierte Token entspricht einer anderen Zielgruppe.",
    },
    "requires-recent-login": {
        en: "This operation is sensitive and requires recent authentication. Log in again before retrying this request.",
        fr: "Cette opération est sensible et nécessite une authentification récente. Reconnectez-vous avant de réessayer cette demande.",
        es: "Esta operación es sensible y requiere autenticación reciente. Vuelve a iniciar sesión antes de reintentar esta solicitud.",
        it: "Questa operazione è sensibile e richiede un'autenticazione recente. Accedi di nuovo prima di ripetere questa richiesta.",
        de: "Dieser Vorgang ist vertraulich und erfordert eine kürzlich erfolgte Authentifizierung. Melden Sie sich erneut an, bevor Sie diese Anfrage wiederholen.",
    },
    "dynamic-link-not-activated": {
        en: "Please activate Dynamic Links in the Firebase Console and agree to the terms and conditions.",
        fr: "Veuillez activer les liens dynamiques dans la console Firebase et accepter les termes et conditions.",
        es: "Activa Dynamic Links en Firebase console y acepta los términos y condiciones.",
        it: "Attiva Dynamic Links in Firebase console e accetta i termini e le condizioni.",
        de: "Bitte aktivieren Sie Dynamic Links in der Firebase Console und stimmen Sie den Nutzungsbedingungen zu.",
    },
    "email-change-needs-verification": {
        en: "Multi-factor users must always have a verified email.",
        fr: "Les utilisateurs multifacteur doivent toujours avoir une adresse e-mail vérifiée.",
        es: "Los usuarios multifactor siempre deben tener un correo electrónico verificado.",
        it: "Gli utenti multifattoriali devono sempre disporre di un'email verificata.",
        de: "Multi-Faktor-Nutzer müssen immer eine verifizierte E-Mail-Adresse haben.",
    },
    "email-already-in-use": {
        en: "The email address is already in use by another account.",
        fr: "L'adresse email est déjà utilisée par un autre compte.",
        es: "La dirección de correo electrónico ya está en uso por otra cuenta.",
        it: "L'indirizzo email è già in uso da un altro account.",
        de: "Die E-Mail-Adresse wird bereits von einem anderen Konto verwendet.",
    },
    "expired-action-code": {
        en: "The action code has expired. ",
        fr: "Le code d'action a expiré. ",
        es: "El código de acción expiró. ",
        it: "Il codice azione è scaduto. ",
        de: "Der Aktionscode ist abgelaufen. ",
    },
    "cancelled-popup-request": {
        en: "This operation has been cancelled due to another conflicting popup being opened.",
        fr: "Cette opération a été annulée en raison de l'ouverture d'une autre fenêtre contextuelle conflictuelle.",
        es: "Esta operación se canceló debido a que se abrió otra ventana emergente en conflicto.",
        it: "Questa operazione è stata annullata a causa dell'apertura di un'altra finestra popup in conflitto.",
        de: "Dieser Vorgang wurde abgebrochen, da ein anderes Popup-Fenster geöffnet wurde.",
    },
    "internal-error": {
        en: "An internal error has occurred.",
        fr: "Une erreur interne s'est produite.",
        es: "Se produjo un error interno.",
        it: "Si è verificato un errore interno.",
        de: "Es ist ein interner Fehler aufgetreten.",
    },
    "invalid-app-credential": {
        en: "The phone verification request contains an invalid application verifier. The reCAPTCHA token response is either invalid or expired.",
        fr: "La demande de vérification par téléphone contient un vérificateur d'application non valide. La réponse du jeton reCAPTCHA est soit invalide, soit expirée.",
        es: "La solicitud de verificación telefónica contiene un verificador de aplicación no válido. La respuesta del token de reCAPTCHA no es válida o expiró.",
        it: "La richiesta di verifica telefonica contiene un verificatore di applicazione non valido. La risposta del token reCAPTCHA non è valida o è scaduta.",
        de: "Die Telefonüberprüfungsanfrage enthält einen ungültigen Anwendungsbestätiger. Die reCAPTCHA-Tokenantwort ist entweder ungültig oder abgelaufen.",
    },
    "invalid-app-id": {
        en: "The mobile app identifier is not registed for the current project.",
        fr: "L'identifiant de l'application mobile n'est pas enregistré pour le projet en cours.",
        es: "El identificador de la aplicación móvil no está registrado para el proyecto actual.",
        it: "L'identificatore dell'app mobile non è registrato per il progetto corrente.",
        de: "Die Kennung der mobilen App ist für das aktuelle Projekt nicht registriert.",
    },
    "invalid-user-token": {
        en: "This user's credential isn't valid for this project. This can happen if the user's token has been tampered with, or if the user isn't for the project associated with this API key.",
        fr: "Les informations d'identification de cet utilisateur ne sont pas valides pour ce projet. Cela peut se produire si le jeton de l'utilisateur a été falsifié ou si l'utilisateur ne participe pas au projet associé à cette clé API.",
        es: "Las credenciales de este usuario no son válidas para este proyecto. Esto puede suceder si se manipuló el token del usuario o si este no forma parte del proyecto asociado con esta clave API.",
        it: "Le credenziali di questo utente non sono valide per questo progetto. Ciò può accadere se il token dell'utente è stato manomesso o se l'utente non fa parte del progetto associato a questa chiave API.",
        de: "Die Anmeldedaten dieses Benutzers sind für dieses Projekt nicht gültig. Dies kann passieren, wenn das Token des Benutzers manipuliert wurde oder wenn der Benutzer nicht zu dem Projekt gehört, das mit diesem API-Schlüssel verknüpft ist.",
    },
    "invalid-auth-event": {
        en: "An internal error has occurred.",
        fr: "Une erreur interne s'est produite.",
        es: "Se produjo un error interno.",
        it: "Si è verificato un errore interno.",
        de: "Es ist ein interner Fehler aufgetreten.",
    },
    "invalid-verification-code": {
        en: "The SMS verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user.",
        fr: "Le code de vérification SMS utilisé pour créer les informations d'authentification du téléphone n'est pas valide. Veuillez renvoyer le SMS du code de vérification et assurez-vous d'utiliser le code de vérification fourni par l'utilisateur.",
        es: "El código de verificación SMS que se usó para crear las credenciales de autenticación telefónica no es válido. Vuelve a enviar el SMS con el código de verificación y asegúrate de usar el código que proporcionó el usuario.",
        it: "Il codice di verifica SMS utilizzato per creare le credenziali di autenticazione telefonica non è valido. Invia di nuovo l'SMS con il codice di verifica e assicurati di utilizzare il codice fornito dall'utente.",
        de: "Der SMS-Bestätigungscode, der zum Erstellen der Telefonauthentifizierungsdaten verwendet wurde, ist ungültig. Bitte senden Sie die SMS mit dem Bestätigungscode erneut und stellen Sie sicher, dass Sie den vom Benutzer angegebenen Bestätigungscode verwenden.",
    },
    "invalid-continue-uri": {
        en: "The continue URL provided in the request is invalid.",
        fr: "L'URL de suite fournie dans la demande n'est pas valide.",
        es: "La URL de continuación proporcionada en la solicitud no es válida.",
        it: "L'URL di continuazione fornito nella richiesta non è valido.",
        de: "Die in der Anfrage angegebene Weiterleitungs-URL ist ungültig.",
    },
    "invalid-cordova-configuration": {
        en: "The following Cordova plugins must be installed to enable OAuth sign-in: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser and cordova-plugin-customurlscheme.",
        fr: "Les plugins Cordova suivants doivent être installés pour activer la connexion OAuth : cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser et cordova-plugin-customurlscheme.",
        es: "Debes instalar los siguientes complementos de Cordova para habilitar el acceso con OAuth: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser y cordova-plugin-customurlscheme.",
        it: "Per abilitare l'accesso con OAuth, è necessario installare i seguenti plugin Cordova: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser e cordova-plugin-customurlscheme.",
        de: "Die folgenden Cordova-Plugins müssen installiert sein, um die OAuth-Anmeldung zu aktivieren: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser und cordova-plugin-customurlscheme.",
    },
    "invalid-custom-token": {
        en: "The custom token format is incorrect. Please check the documentation.",
        fr: "Le format du jeton personnalisé est incorrect. Veuillez consulter la documentation.",
        es: "El formato del token personalizado es incorrecto. Consulta la documentación.",
        it: "Il formato del token personalizzato non è corretto. Consulta la documentazione.",
        de: "Das Format des benutzerdefinierten Tokens ist falsch. Bitte überprüfen Sie die Dokumentation.",
    },
    "invalid-dynamic-link-domain": {
        en: "The provided dynamic link domain is not configured or authorized for the current project.",
        fr: "Le domaine de lien dynamique fourni n'est pas configuré ou autorisé pour le projet en cours.",
        es: "El dominio de enlace dinámico proporcionado no está configurado ni autorizado para el proyecto actual.",
        it: "Il dominio di link dinamico fornito non è configurato o autorizzato per il progetto corrente.",
        de: "Die angegebene Dynamic Link-Domain ist für das aktuelle Projekt nicht konfiguriert oder autorisiert.",
    },
    "invalid-email": {
        en: "The email address is badly formatted.",
        fr: "L'adresse email est mal formatée.",
        es: "El formato de la dirección de correo electrónico es incorrecto.",
        it: "Il formato dell'indirizzo email non è corretto.",
        de: "Die E-Mail-Adresse ist falsch formatiert.",
    },
    "invalid-api-key": {
        en: "Your API key is invalid, please check you have copied it correctly.",
        fr: "Votre clé API n'est pas valide, veuillez vérifier que vous l'avez copiée correctement.",
        es: "Tu clave API no es válida. Verifica que la hayas copiado correctamente.",
        it: "La tua chiave API non è valida. Verifica di averla copiata correttamente.",
        de: "Ihr API-Schlüssel ist ungültig. Bitte überprüfen Sie, ob Sie ihn richtig kopiert haben.",
    },
    "invalid-cert-hash": {
        en: "The SHA-1 certificate hash provided is invalid.",
        fr: "Le hachage du certificat SHA-1 fourni n'est pas valide.",
        es: "El hash de certificado SHA-1 proporcionado no es válido.",
        it: "L'hash del certificato SHA-1 fornito non è valido.",
        de: "Der angegebene SHA-1-Zertifikats-Hash ist ungültig.",
    },
    "invalid-credential": {
        en: "The supplied auth credential is malformed or has expired.",
        fr: "Les informations d'authentification fournies sont mal formées ou ont expiré.",
        es: "Las credenciales de autenticación proporcionadas tienen un formato incorrecto o expiraron.",
        it: "Le credenziali di autenticazione fornite non sono valide o sono scadute.",
        de: "Die angegebenen Authentifizierungsdaten sind fehlerhaft oder abgelaufen.",
    },
    "invalid-message-payload": {
        en: "The email template corresponding to this action contains invalid characters in its message. Please fix by going to the Auth email templates section in the Firebase Console.",
        fr: "Le modèle d'e-mail correspondant à cette action contient des caractères non valides dans son message. Veuillez corriger en accédant à la section Modèles d'e-mail d'authentification dans la console Firebase.",
        es: 'La plantilla de correo electrónico correspondiente a esta acción contiene caracteres no válidos en su mensaje. Corrígela en la sección "Plantillas de correo electrónico de autenticación" de Firebase console.',
        it: "Il modello email corrispondente a questa azione contiene caratteri non validi nel messaggio. Correggilo accedendo alla sezione Modelli email di autenticazione in Firebase console.",
        de: 'Die E-Mail-Vorlage für diese Aktion enthält ungültige Zeichen in der Nachricht. Bitte korrigieren Sie dies im Abschnitt "E-Mail-Vorlagen für die Authentifizierung" in der Firebase Console.',
    },
    "invalid-multi-factor-session": {
        en: "The request does not contain a valid proof of first factor successful sign-in.",
        fr: "La demande ne contient pas de preuve valide de connexion réussie au premier facteur.",
        es: "La solicitud no contiene una prueba válida del inicio de sesión correcto con el primer factor.",
        it: "La richiesta non contiene una prova valida dell'accesso riuscito con il primo fattore.",
        de: "Die Anfrage enthält keinen gültigen Nachweis für eine erfolgreiche Anmeldung mit dem ersten Faktor.",
    },
    "invalid-oauth-provider": {
        en: "EmailAuthProvider is not supported for this operation. This operation only supports OAuth providers.",
        fr: "EmailAuthProvider n'est pas pris en charge pour cette opération. Cette opération ne prend en charge que les fournisseurs OAuth.",
        es: "EmailAuthProvider no es compatible con esta operación. Esta solo admite proveedores de OAuth.",
        it: "EmailAuthProvider non è supportato per questa operazione. Questa operazione supporta solo i provider OAuth.",
        de: "EmailAuthProvider wird für diesen Vorgang nicht unterstützt. Dieser Vorgang unterstützt nur OAuth-Anbieter.",
    },
    "invalid-oauth-client-id": {
        en: "The OAuth client ID provided is either invalid or does not match the specified API key.",
        fr: "L'ID client OAuth fourni n'est pas valide ou ne correspond pas à la clé API spécifiée.",
        es: "El ID de cliente de OAuth proporcionado no es válido o no coincide con la clave API especificada.",
        it: "L'ID client OAuth fornito non è valido o non corrisponde alla chiave API specificata.",
        de: "Die angegebene OAuth-Client-ID ist entweder ungültig oder stimmt nicht mit dem angegebenen API-Schlüssel überein.",
    },
    "unauthorized-domain": {
        en: "This domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console.",
        fr: "Ce domaine n'est pas autorisé pour les opérations OAuth pour votre projet Firebase. Modifiez la liste des domaines autorisés depuis la console Firebase.",
        es: "Este dominio no está autorizado para las operaciones de OAuth en tu proyecto de Firebase. Edita la lista de dominios autorizados en Firebase console.",
        it: "Questo dominio non è autorizzato per le operazioni OAuth per il tuo progetto Firebase. Modifica l'elenco dei domini autorizzati da Firebase console.",
        de: "Diese Domain ist für OAuth-Vorgänge für Ihr Firebase-Projekt nicht autorisiert. Bearbeiten Sie die Liste der autorisierten Domains in der Firebase Console.",
    },
    "invalid-action-code": {
        en: "The action code is invalid. This can happen if the code is malformed, expired, or has already been used.",
        fr: "Le code d'action n'est pas valide. Cela peut se produire si le code est mal formé, a expiré ou a déjà été utilisé.",
        es: "El código de acción no es válido. Esto puede suceder si el código tiene un formato incorrecto, expiró o ya se usó.",
        it: "Il codice azione non è valido. Questo può accadere se il codice non è valido, è scaduto o è già stato utilizzato.",
        de: "Der Aktionscode ist ungültig. Dies kann passieren, wenn der Code fehlerhaft ist, abgelaufen ist oder bereits verwendet wurde.",
    },
    "wrong-password": {
        en: "The password is invalid or the user does not have a password.",
        fr: "Le mot de passe n'est pas valide ou l'utilisateur n'a pas de mot de passe.",
        es: "La contraseña no es válida o el usuario no tiene una contraseña.",
        it: "La password non è valida o l'utente non ha una password.",
        de: "Das Passwort ist ungültig oder der Benutzer hat kein Passwort.",
    },
    "invalid-persistence-type": {
        en: "The specified persistence type is invalid. It can only be local, session or none.",
        fr: "Le type de persistance spécifié n'est pas valide. Il ne peut être que local, session ou aucun.",
        es: "El tipo de persistencia especificado no es válido. Solo puede ser local, de sesión o ninguno.",
        it: "Il tipo di persistenza specificato non è valido. Può essere solo locale, di sessione o nessuno.",
        de: 'Der angegebene Persistenztyp ist ungültig. Er kann nur "local", "session" oder "none" sein.',
    },
    "invalid-phone-number": {
        en: "The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code].",
        fr: "Le format du numéro de téléphone fourni est incorrect. Veuillez saisir le numéro de téléphone dans un format qui peut être analysé au format E.164. Les numéros de téléphone E.164 sont écrits au format [+][code du pays][numéro d'abonné incluant indicatif régional].",
        es: "El formato del número de teléfono proporcionado es incorrecto. Ingresa el número de teléfono en un formato que se pueda analizar en formato E.164. Los números de teléfono E.164 se escriben en el formato [+][código de país][número de suscriptor, incluido el código de área].",
        it: "Il formato del numero di telefono fornito non è corretto. Inserisci il numero di telefono in un formato che possa essere analizzato nel formato E.164. I numeri di telefono E.164 sono scritti nel formato [+][prefisso internazionale][numero di telefono comprensivo di prefisso].",
        de: "Das Format der angegebenen Telefonnummer ist falsch. Bitte geben Sie die Telefonnummer in einem Format ein, das in das E.164-Format analysiert werden kann. E.164-Telefonnummern werden im Format [+][Ländercode][Teilnehmernummer einschließlich Vorwahl] geschrieben.",
    },
    "invalid-provider-id": {
        en: "The specified provider ID is invalid.",
        fr: "L'ID du fournisseur spécifié n'est pas valide.",
        es: "El ID de proveedor especificado no es válido.",
        it: "L'ID provider specificato non è valido.",
        de: "Die angegebene Anbieter-ID ist ungültig.",
    },
    "invalid-recipient-email": {
        en: "The email corresponding to this action failed to send as the provided recipient email address is invalid.",
        fr: "L'e-mail correspondant à cette action n'a pas pu être envoyé car l'adresse e-mail du destinataire fournie n'est pas valide.",
        es: "No se pudo enviar el correo electrónico correspondiente a esta acción porque la dirección de correo electrónico del destinatario proporcionada no es válida.",
        it: "L'email corrispondente a questa azione non è stata inviata perché l'indirizzo email del destinatario fornito non è valido.",
        de: "Die E-Mail zu dieser Aktion konnte nicht gesendet werden, da die angegebene E-Mail-Adresse des Empfängers ungültig ist.",
    },
    "invalid-sender": {
        en: "The email template corresponding to this action contains an invalid sender email or name. Please fix by going to the Auth email templates section in the Firebase Console.",
        fr: "Le modèle d'e-mail correspondant à cette action contient une adresse e-mail ou un nom d'expéditeur non valide. Veuillez le corriger en accédant à la section Modèles d'e-mail d'authentification dans la console Firebase.",
        es: 'La plantilla de correo electrónico correspondiente a esta acción contiene un nombre o una dirección de correo electrónico de remitente no válidos. Corrígela en la sección "Plantillas de correo electrónico de autenticación" de Firebase console.',
        it: "Il modello email corrispondente a questa azione contiene un nome o un indirizzo email del mittente non validi. Correggilo accedendo alla sezione Modelli email di autenticazione in Firebase console.",
        de: 'Die E-Mail-Vorlage für diese Aktion enthält eine ungültige Absender-E-Mail-Adresse oder einen ungültigen Absendernamen. Bitte korrigieren Sie dies im Abschnitt "E-Mail-Vorlagen für die Authentifizierung" in der Firebase Console.',
    },
    "invalid-verification-id": {
        en: "The verification ID used to create the phone auth credential is invalid.",
        fr: "L'ID de vérification utilisé pour créer les informations d'identification du téléphone n'est pas valide.",
        es: "El ID de verificación que se usó para crear las credenciales de autenticación telefónica no es válido.",
        it: "L'ID di verifica utilizzato per creare le credenziali di autenticazione telefonica non è valido.",
        de: "Die Überprüfungs-ID, die zum Erstellen der Telefonauthentifizierungsdaten verwendet wurde, ist ungültig.",
    },
    "invalid-tenant-id": {
        en: "The Auth instance's tenant ID is invalid.",
        fr: "L'ID de locataire de l'instance Auth n'est pas valide.",
        es: "El ID de inquilino de la instancia de autenticación no es válido.",
        it: "L'ID tenant dell'istanza di autenticazione non è valido.",
        de: "Die Mandanten-ID der Auth-Instanz ist ungültig.",
    },
    "multi-factor-info-not-found": {
        en: "The user does not have a second factor matching the identifier provided.",
        fr: "L'utilisateur ne dispose pas d'un deuxième facteur correspondant à l'identifiant fourni.",
        es: "El usuario no tiene un segundo factor que coincida con el identificador proporcionado.",
        it: "L'utente non ha un secondo fattore corrispondente all'identificatore fornito.",
        de: "Der Benutzer verfügt nicht über einen zweiten Faktor, der mit der angegebenen Kennung übereinstimmt.",
    },
    "multi-factor-auth-required": {
        en: "Proof of ownership of a second factor is required to complete sign-in.",
        fr: "Une preuve de propriété d'un deuxième facteur est requise pour finaliser la connexion.",
        es: "Se requiere una prueba de propiedad de un segundo factor para completar el inicio de sesión.",
        it: "È richiesta una prova di proprietà di un secondo fattore per completare l'accesso.",
        de: "Zum Abschließen der Anmeldung ist ein Nachweis über den Besitz eines zweiten Faktors erforderlich.",
    },
    "missing-android-pkg-name": {
        en: "An Android Package Name must be provided if the Android App is required to be installed.",
        fr: "Un nom de package Android doit être fourni si l'application Android doit être installée.",
        es: "Se debe proporcionar un nombre de paquete de Android si se requiere que la aplicación de Android esté instalada.",
        it: "È necessario fornire un nome pacchetto Android se è necessario installare l'app Android.",
        de: "Ein Android-Paketname muss angegeben werden, wenn die Android-App installiert werden muss.",
    },
    "auth-domain-config-required": {
        en: "Be sure to include authDomain when calling firebase.initializeApp(), by following the instructions in the Firebase console.",
        fr: "Assurez-vous d'inclure authDomain lors de l'appel de firebase.initializeApp(), en suivant les instructions de la console Firebase.",
        es: "Asegúrate de incluir authDomain cuando llames a firebase.initializeApp() mediante las instrucciones de Firebase console.",
        it: "Assicurati di includere authDomain quando chiami firebase.initializeApp(), seguendo le istruzioni in Firebase console.",
        de: "Stellen Sie sicher, dass Sie authDomain beim Aufruf von firebase.initializeApp() angeben, indem Sie die Anweisungen in der Firebase Console befolgen.",
    },
    "missing-app-credential": {
        en: "The phone verification request is missing an application verifier assertion. A reCAPTCHA response token needs to be provided.",
        fr: "Il manque une assertion du vérificateur d'application dans la demande de vérification téléphonique. Un jeton de réponse reCAPTCHA doit être fourni.",
        es: "A la solicitud de verificación telefónica le falta una aserción del verificador de la aplicación. Se debe proporcionar un token de respuesta de reCAPTCHA.",
        it: "Nella richiesta di verifica telefonica manca un'asserzione del verificatore dell'applicazione. È necessario fornire un token di risposta reCAPTCHA.",
        de: "Der Telefonüberprüfungsanfrage fehlt eine Bestätigung des Anwendungsbestätigers. Es muss ein reCAPTCHA-Antwort-Token angegeben werden.",
    },
    "missing-verification-code": {
        en: "The phone auth credential was created with an empty SMS verification code.",
        fr: "L'identifiant d'authentification du téléphone a été créé avec un code de vérification SMS vide.",
        es: "Las credenciales de autenticación telefónica se crearon con un código de verificación SMS vacío.",
        it: "Le credenziali di autenticazione telefonica sono state create con un codice di verifica SMS vuoto.",
        de: "Die Telefonauthentifizierungsdaten wurden mit einem leeren SMS-Bestätigungscode erstellt.",
    },
    "missing-continue-uri": {
        en: "A continue URL must be provided in the request.",
        fr: "Une URL de continuation doit être fournie dans la demande.",
        es: "Se debe proporcionar una URL de continuación en la solicitud.",
        it: "È necessario fornire un URL di continuazione nella richiesta.",
        de: "In der Anfrage muss eine Weiterleitungs-URL angegeben werden.",
    },
    "missing-iframe-start": {
        en: "An internal error has occurred.",
        fr: "Une erreur interne s'est produite.",
        es: "Se produjo un error interno.",
        it: "Si è verificato un errore interno.",
        de: "Es ist ein interner Fehler aufgetreten.",
    },
    "missing-ios-bundle-id": {
        en: "An iOS Bundle ID must be provided if an App Store ID is provided.",
        fr: "Un identifiant de bundle iOS doit être fourni si un identifiant App Store est fourni.",
        es: "Se debe proporcionar un ID de paquete de iOS si se proporciona un ID de App Store.",
        it: "È necessario fornire un ID bundle iOS se viene fornito un ID App Store.",
        de: "Eine iOS-Bundle-ID muss angegeben werden, wenn eine App Store-ID angegeben wird.",
    },
    "missing-multi-factor-info": {
        en: "No second factor identifier is provided.",
        fr: "Aucun identifiant de deuxième facteur n'est fourni.",
        es: "No se proporciona ningún identificador de segundo factor.",
        it: "Non è stato fornito alcun identificatore del secondo fattore.",
        de: "Es wurde keine zweite Faktorkennung angegeben.",
    },
    "missing-multi-factor-session": {
        en: "The request is missing proof of first factor successful sign-in.",
        fr: "Il manque dans la demande la preuve d'une connexion réussie au premier facteur.",
        es: "En la solicitud, falta la prueba de inicio de sesión correcto con el primer factor.",
        it: "Nella richiesta manca la prova dell'accesso riuscito con il primo fattore.",
        de: "Der Anfrage fehlt der Nachweis für eine erfolgreiche Anmeldung mit dem ersten Faktor.",
    },
    "missing-or-invalid-nonce": {
        en: "The request does not contain a valid nonce. This can occur if the SHA-256 hash of the provided raw nonce does not match the hashed nonce in the ID token payload.",
        fr: "La demande ne contient pas de nom occasionnel valide. Cela peut se produire si le hachage SHA-256 du nom occasionnel brut fourni ne correspond pas au nom occasionnel haché dans la charge utile du jeton d'identification.",
        es: "La solicitud no contiene un valor de nonce válido. Esto puede ocurrir si el hash SHA-256 del valor de nonce sin procesar proporcionado no coincide con el valor de nonce con hash en la carga útil del token de ID.",
        it: "La richiesta non contiene un nonce valido. Questo può verificarsi se l'hash SHA-256 del nonce non elaborato fornito non corrisponde al nonce sottoposto a hashing nel payload del token ID.",
        de: "Die Anfrage enthält keine gültige Nonce. Dies kann auftreten, wenn der SHA-256-Hash der bereitgestellten Raw-Nonce nicht mit der Hash-Nonce in der ID-Token-Payload übereinstimmt.",
    },
    "missing-phone-number": {
        en: "To send verification codes, provide a phone number for the recipient.",
        fr: "Pour envoyer des codes de vérification, fournissez un numéro de téléphone pour le destinataire.",
        es: "Para enviar códigos de verificación, proporciona un número de teléfono para el destinatario.",
        it: "Per inviare i codici di verifica, fornisci un numero di telefono per il destinatario.",
        de: "Um Bestätigungscodes zu senden, geben Sie eine Telefonnummer für den Empfänger an.",
    },
    "missing-verification-id": {
        en: "The phone auth credential was created with an empty verification ID.",
        fr: "L'identifiant d'authentification du téléphone a été créé avec un identifiant de vérification vide.",
        es: "Las credenciales de autenticación telefónica se crearon con un ID de verificación vacío.",
        it: "Le credenziali di autenticazione telefonica sono state create con un ID di verifica vuoto.",
        de: "Die Telefonauthentifizierungsdaten wurden mit einer leeren Überprüfungs-ID erstellt.",
    },
    "app-deleted": {
        en: "This instance of FirebaseApp has been deleted.",
        fr: "Cette instance de FirebaseApp a été supprimée.",
        es: "Esta instancia de FirebaseApp se borró.",
        it: "Questa istanza di FirebaseApp è stata eliminata.",
        de: "Diese Instanz von FirebaseApp wurde gelöscht.",
    },
    "account-exists-with-different-credential": {
        en: "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.",
        fr: "Un compte existe déjà avec la même adresse e-mail mais des identifiants de connexion différents. Connectez-vous en utilisant un fournisseur associé à cette adresse e-mail.",
        es: "Ya existe una cuenta con la misma dirección de correo electrónico, pero con credenciales de inicio de sesión diferentes. Accede con un proveedor asociado a esta dirección de correo electrónico.",
        it: "Esiste già un account con lo stesso indirizzo email ma con credenziali di accesso diverse. Accedi utilizzando un provider associato a questo indirizzo email.",
        de: "Es besteht bereits ein Konto mit derselben E-Mail-Adresse, aber anderen Anmeldeinformationen. Melden Sie sich mit einem Anbieter an, der mit dieser E-Mail-Adresse verknüpft ist.",
    },
    "network-request-failed": {
        en: "A network error (such as timeout, interrupted connection or unreachable host) has occurred.",
        fr: "Une erreur réseau (telle qu'un délai d'attente, une connexion interrompue ou un hôte inaccessible) s'est produite.",
        es: "Se produjo un error de red (como tiempo de espera agotado, conexión interrumpida o host inalcanzable).",
        it: "Si è verificato un errore di rete (ad esempio timeout, connessione interrotta o host irraggiungibile).",
        de: "Es ist ein Netzwerkfehler aufgetreten (z. B. Timeout, unterbrochene Verbindung oder unerreichbarer Host).",
    },
    "no-auth-event": {
        en: "An internal error has occurred.",
        fr: "Une erreur interne s'est produite.",
        es: "Se produjo un error interno.",
        it: "Si è verificato un errore interno.",
        de: "Es ist ein interner Fehler aufgetreten.",
    },
    "no-such-provider": {
        en: "User was not linked to an account with the given provider.",
        fr: "L'utilisateur n'était pas lié à un compte auprès du fournisseur indiqué.",
        es: "El usuario no se vinculó a una cuenta con el proveedor dado.",
        it: "L'utente non è stato collegato a un account con il provider specificato.",
        de: "Der Benutzer war nicht mit einem Konto beim angegebenen Anbieter verknüpft.",
    },
    "null-user": {
        en: "A null user object was provided as the argument for an operation which requires a non-null user object.",
        fr: "Un objet utilisateur nul a été fourni comme argument pour une opération qui nécessite un objet utilisateur non nul.",
        es: "Se proporcionó un objeto de usuario nulo como argumento para una operación que requiere un objeto de usuario no nulo.",
        it: "È stato fornito un oggetto utente nullo come argomento per un'operazione che richiede un oggetto utente non nullo.",
        de: "Es wurde ein Nullbenutzerobjekt als Argument für einen Vorgang bereitgestellt, der ein Nicht-Nullbenutzerobjekt erfordert.",
    },
    "operation-not-allowed": {
        en: "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.",
        fr: "Le fournisseur de connexion indiqué est désactivé pour ce projet Firebase. Activez-le dans la console Firebase, sous l'onglet Méthode de connexion de la section Auth.",
        es: "El proveedor de inicio de sesión dado está inhabilitado para este proyecto de Firebase. HabilÍtalo en Firebase console, en la pestaña del método de inicio de sesión de la sección de autenticación.",
        it: "Il provider di accesso specificato è disabilitato per questo progetto Firebase. Abilitalo in Firebase console, nella scheda del metodo di accesso della sezione Autenticazione.",
        de: 'Der angegebene Anmeldeanbieter ist für dieses Firebase-Projekt deaktiviert. Aktivieren Sie ihn in der Firebase Console auf der Registerkarte "Anmeldemethode" im Abschnitt "Authentifizierung".',
    },
    "operation-not-supported-in-this-environment": {
        en: 'This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.',
        fr: "Cette opération n'est pas prise en charge dans l'environnement sur lequel cette application est exécutée. \"location.protocol\" doit être http, https ou chrome-extension et le stockage Web doit être activé.",
        es: 'Esta operación no es compatible con el entorno en el que se ejecuta esta aplicación. "location.protocol" debe ser http, https o chrome-extension, y el almacenamiento web debe estar habilitado.',
        it: "Questa operazione non è supportata nell'ambiente in cui è in esecuzione l'applicazione. \"location.protocol\" deve essere http, https o chrome-extension e l'archiviazione web deve essere abilitata.",
        de: 'Dieser Vorgang wird in der Umgebung, in der diese Anwendung ausgeführt wird, nicht unterstützt. "location.protocol" muss http, https oder chrome-extension sein und Webspeicher muss aktiviert sein.',
    },
    "popup-blocked": {
        en: "Unable to establish a connection with the popup. It may have been blocked by the browser.",
        fr: "Impossible d'établir une connexion avec le popup. Il a peut-être été bloqué par le navigateur.",
        es: "No se pudo establecer una conexión con la ventana emergente. Es posible que el navegador la haya bloqueado.",
        it: "Impossibile stabilire una connessione con la finestra popup. Potrebbe essere stata bloccata dal browser.",
        de: "Es konnte keine Verbindung mit dem Popup-Fenster hergestellt werden. Es wurde möglicherweise vom Browser blockiert.",
    },
    "popup-closed-by-user": {
        en: "The popup has been closed by the user before finalizing the operation.",
        fr: "La popup a été fermée par l'utilisateur avant de finaliser l'opération.",
        es: "El usuario cerró la ventana emergente antes de finalizar la operación.",
        it: "La finestra popup è stata chiusa dall'utente prima di finalizzare l'operazione.",
        de: "Das Popup-Fenster wurde vom Benutzer geschlossen, bevor der Vorgang abgeschlossen wurde.",
    },
    "provider-already-linked": {
        en: "User can only be linked to one identity for the given provider.",
        fr: "L'utilisateur ne peut être lié qu'à une seule identité pour le fournisseur donné.",
        es: "El usuario solo se puede vincular a una identidad para el proveedor dado.",
        it: "L'utente può essere collegato a una sola identità per il provider specificato.",
        de: "Der Benutzer kann nur mit einer Identität für den angegebenen Anbieter verknüpft werden.",
    },
    "quota-exceeded": {
        en: "The project's quota for this operation has been exceeded.",
        fr: "Le quota du projet pour cette opération a été dépassé.",
        es: "Se excedió la cuota del proyecto para esta operación.",
        it: "La quota del progetto per questa operazione è stata superata.",
        de: "Das Kontingent des Projekts für diesen Vorgang wurde überschritten.",
    },
    "redirect-cancelled-by-user": {
        en: "The redirect operation has been cancelled by the user before finalizing.",
        fr: "L'opération de redirection a été annulée par l'utilisateur avant d'être finalisée.",
        es: "El usuario canceló la operación de redireccionamiento antes de finalizarla.",
        it: "L'operazione di reindirizzamento è stata annullata dall'utente prima del completamento.",
        de: "Der Umleitungsvorgang wurde vom Benutzer vor dem Abschluss abgebrochen.",
    },
    "redirect-operation-pending": {
        en: "A redirect sign-in operation is already pending.",
        fr: "Une opération de connexion par redirection est déjà en attente.",
        es: "Ya hay una operación de inicio de sesión de redireccionamiento pendiente.",
        it: "È già in corso un'operazione di accesso con reindirizzamento.",
        de: "Ein Umleitungsanmeldevorgang ist bereits ausstehend.",
    },
    "rejected-credential": {
        en: "The request contains malformed or mismatching credentials.",
        fr: "La demande contient des informations d'identification mal formées ou incompatibles.",
        es: "La solicitud contiene credenciales con formato incorrecto o que no coinciden.",
        it: "La richiesta contiene credenziali non valide o non corrispondenti.",
        de: "Die Anfrage enthält fehlerhafte oder nicht übereinstimmende Anmeldeinformationen.",
    },
    "second-factor-already-in-use": {
        en: "The second factor is already enrolled on this account.",
        fr: "Le deuxième facteur est déjà inscrit sur ce compte.",
        es: "El segundo factor ya está registrado en esta cuenta.",
        it: "Il secondo fattore è già registrato su questo account.",
        de: "Der zweite Faktor ist bereits in diesem Konto registriert.",
    },
    "maximum-second-factor-count-exceeded": {
        en: "The maximum allowed number of second factors on a user has been exceeded.",
        fr: "Le nombre maximum autorisé de seconds facteurs sur un utilisateur a été dépassé.",
        es: "Se excedió la cantidad máxima permitida de segundos factores en un usuario.",
        it: "È stato superato il numero massimo consentito di secondi fattori su un utente.",
        de: "Die maximal zulässige Anzahl von zweiten Faktoren für einen Benutzer wurde überschritten.",
    },
    "tenant-id-mismatch": {
        en: "The provided tenant ID does not match the Auth instance's tenant ID",
        fr: "L'ID de locataire fourni ne correspond pas à l'ID de locataire de l'instance Auth",
        es: "El ID de inquilino proporcionado no coincide con el ID de inquilino de la instancia de autenticación",
        it: "L'ID tenant fornito non corrisponde all'ID tenant dell'istanza di autenticazione",
        de: "Die angegebene Mandanten-ID stimmt nicht mit der Mandanten-ID der Auth-Instanz überein",
    },
    timeout: {
        en: "The operation has timed out.",
        fr: "L'opération a expiré.",
        es: "La operación expiró.",
        it: "L'operazione è andata in timeout.",
        de: "Der Vorgang ist abgelaufen.",
    },
    "user-token-expired": {
        en: "The user's credential is no longer valid. The user must sign in again.",
        fr: "Les identifiants de l'utilisateur ne sont plus valides. L'utilisateur doit se reconnecter.",
        es: "Las credenciales del usuario ya no son válidas. El usuario debe volver a iniciar sesión.",
        it: "Le credenziali dell'utente non sono più valide. L'utente deve accedere di nuovo.",
        de: "Die Anmeldeinformationen des Benutzers sind nicht mehr gültig. Der Benutzer muss sich erneut anmelden.",
    },
    "too-many-requests": {
        en: "We have blocked all requests from this device due to unusual activity. Try again later.",
        fr: "Nous avons bloqué toutes les demandes provenant de cet appareil en raison d'une activité inhabituelle. Réessayez plus tard.",
        es: "Bloqueamos todas las solicitudes de este dispositivo debido a actividad inusual. Vuelve a intentarlo más tarde.",
        it: "Abbiamo bloccato tutte le richieste da questo dispositivo a causa di attività insolite. Riprova più tardi.",
        de: "Wir haben alle Anfragen von diesem Gerät aufgrund ungewöhnlicher Aktivitäten blockiert. Versuchen Sie es später erneut.",
    },
    "unauthorized-continue-uri": {
        en: "The domain of the continue URL is not whitelisted.  Please whitelist the domain in the Firebase console.",
        fr: "Le domaine de l'URL de suite n'est pas sur liste blanche. Veuillez ajouter le domaine à la liste blanche dans la console Firebase.",
        es: "El dominio de la URL de continuación no está en la lista blanca. Agrégalo a la lista blanca en Firebase console.",
        it: "Il dominio dell'URL di continuazione non è presente nella whitelist. Aggiungilo alla whitelist in Firebase console.",
        de: "Die Domain der Weiterleitungs-URL ist nicht auf der Whitelist. Bitte fügen Sie die Domain in der Firebase Console zur Whitelist hinzu.",
    },
    "unsupported-first-factor": {
        en: "Enrolling a second factor or signing in with a multi-factor account requires sign-in with a supported first factor.",
        fr: "L'inscription d'un deuxième facteur ou la connexion avec un compte multifacteur nécessite une connexion avec un premier facteur pris en charge.",
        es: "Para registrar un segundo factor o iniciar sesión con una cuenta multifactor, se requiere el inicio de sesión con un primer factor compatible.",
        it: "La registrazione di un secondo fattore o l'accesso con un account multifattore richiede l'accesso con un primo fattore supportato.",
        de: "Das Registrieren eines zweiten Faktors oder die Anmeldung mit einem Multifaktor-Konto erfordert die Anmeldung mit einem unterstützten ersten Faktor.",
    },
    "unsupported-persistence-type": {
        en: "The current environment does not support the specified persistence type.",
        fr: "L'environnement actuel ne prend pas en charge le type de persistance spécifié.",
        es: "El entorno actual no admite el tipo de persistencia especificado.",
        it: "L'ambiente corrente non supporta il tipo di persistenza specificato.",
        de: "Die aktuelle Umgebung unterstützt den angegebenen Persistenztyp nicht.",
    },
    "unsupported-tenant-operation": {
        en: "This operation is not supported in a multi-tenant context.",
        fr: "Cette opération n'est pas supportée dans un contexte multi-tenant.",
        es: "Esta operación no es compatible con un contexto multiinquilino.",
        it: "Questa operazione non è supportata in un contesto multi-tenant.",
        de: "Dieser Vorgang wird in einem Multi-Tenant-Kontext nicht unterstützt.",
    },
    "unverified-email": {
        en: "The operation requires a verified email.",
        fr: "L'opération nécessite un email vérifié.",
        es: "La operación requiere un correo electrónico verificado.",
        it: "L'operazione richiede un'email verificata.",
        de: "Für den Vorgang ist eine verifizierte E-Mail-Adresse erforderlich.",
    },
    "user-cancelled": {
        en: "The user did not grant your application the permissions it requested.",
        fr: "L'utilisateur n'a pas accordé à votre application les autorisations demandées.",
        es: "El usuario no otorgó a tu aplicación los permisos que solicitó.",
        it: "L'utente non ha concesso all'applicazione le autorizzazioni richieste.",
        de: "Der Benutzer hat Ihrer Anwendung nicht die angeforderten Berechtigungen erteilt.",
    },
    "user-not-found": {
        en: "There is no user record corresponding to this identifier. The user may have been deleted.",
        fr: "Il n'existe aucune fiche utilisateur correspondant à cet identifiant. L'utilisateur a peut-être été supprimé.",
        es: "No hay ningún registro de usuario que corresponda a este identificador. Es posible que el usuario se haya borrado.",
        it: "Non esiste alcun record utente corrispondente a questo identificatore. L'utente potrebbe essere stato eliminato.",
        de: "Es gibt keinen Benutzerdatensatz, der dieser Kennung entspricht. Der Benutzer wurde möglicherweise gelöscht.",
    },
    "user-disabled": {
        en: "The user account has been disabled by an administrator.",
        fr: "Le compte utilisateur a été désactivé par un administrateur.",
        es: "Un administrador inhabilitó la cuenta de usuario.",
        it: "L'account utente è stato disabilitato da un amministratore.",
        de: "Das Benutzerkonto wurde von einem Administrator deaktiviert.",
    },
    "user-mismatch": {
        en: "The supplied credentials do not correspond to the previously signed in user.",
        fr: "Les identifiants fournis ne correspondent pas à l'utilisateur précédemment connecté.",
        es: "Las credenciales proporcionadas no corresponden al usuario que inició sesión anteriormente.",
        it: "Le credenziali fornite non corrispondono all'utente che ha eseguito l'accesso in precedenza.",
        de: "Die angegebenen Anmeldeinformationen stimmen nicht mit dem zuvor angemeldeten Benutzer überein.",
    },
    "weak-password": {
        en: "The password must be 6 characters long or more.",
        fr: "Le mot de passe doit comporter 6 caractères ou plus.",
        es: "La contraseña debe tener al menos 6 caracteres.",
        it: "La password deve contenere almeno 6 caratteri.",
        de: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    },
    "web-storage-unsupported": {
        en: "This browser is not supported or 3rd party cookies and data may be disabled.",
        fr: "Ce navigateur n'est pas pris en charge ou les cookies et données tiers peuvent être désactivés.",
        es: "Este navegador no es compatible o es posible que las cookies y los datos de terceros estén inhabilitados.",
        it: "Questo browser non è supportato o i cookie e i dati di terze parti potrebbero essere disabilitati.",
        de: "Dieser Browser wird nicht unterstützt oder Cookies und Daten von Drittanbietern sind möglicherweise deaktiviert.",
    },
};
